name: CI/CD to Raspberry Pi

# main 브랜치에 푸시될 때마다 실행
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Raspberry Pi
    runs-on: [ self-hosted, Linux, ARM64 ]
    steps:
      - uses: actions/checkout@v3
      - name: Restart FastAPI service
        run: sudo systemctl restart fastapi.service
